name: Build and Publish to PyPI
on:
  push:
    tags:
        - 'v*'  # Triggers only on version tag pushes like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/hdsemg-shared/
    env:
      RAW_TAG: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'  # Use the latest 3.10.x version

      - name: Set package Version
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          pip install pyqt5 pyqt5-tools

      - name: Compile Qt resources
        working-directory: src/hdsemg_select
        run: |
          if [ ! -f resources_rc.py ]; then
            echo "Compiling resources.qrc â†’ resources_rc.py"
            pyrcc5 resources.qrc -o resources_rc.py
          else
            echo "resources_rc.py exists, skipping"
          fi
        shell: bash

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
